### ISSUE TITLE
Unhandled exception: module 'pandas' has no attribute 'tslib'

### ISSUE THREAD

**Issue by amotl** [daq-tools/kotori#97]
This request croaks.

https://swarm.hiveeyes.org/api/hiveeyes/25a0e5df-9517-405b-ab14-cb5b514ac9e8/3756782252718325761/1/data.png?include=wght2&from=20160519T040000&to=20160519T170000&renderer=ggplot

**Comment by amotl** [comment]
```
kotori@elbanco:~$ /opt/kotori/bin/python
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
'1.2.5'
```

**Comment by amotl** [comment]
It looks like https://github.com/yhat/ggpy/issues/662#issuecomment-526826798 summarizes the solution.

The correct way should be:

- Change `pandas.tslib.Timestamp` to `pandas.Timestamp`.
- Change `from pandas.lib import Timestamp` to `from pandas import Timestamp`.

**Comment by amotl** [comment]
```python
kotori@elbanco:~$ /opt/kotori/bin/python
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ggplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/kotori/lib/python3.9/site-packages/ggplot/__init__.py", line 19, in <module>
    from .geoms import geom_area, geom_blank, geom_boxplot, geom_line, geom_point, geom_jitter, geom_histogram, geom_density, geom_hline, geom_vline, geom_bar, geom_abline, geom_tile, geom_rect, geom_bin2d, geom_step, geom_text, geom_path, geom_ribbon, geom_now_its_art, geom_violin, geom_errorbar, geom_polygon
  File "/opt/kotori/lib/python3.9/site-packages/ggplot/geoms/__init__.py", line 1, in <module>
    from .geom_abline import geom_abline
  File "/opt/kotori/lib/python3.9/site-packages/ggplot/geoms/geom_abline.py", line 1, in <module>
    from .geom import geom
  File "/opt/kotori/lib/python3.9/site-packages/ggplot/geoms/geom.py", line 3, in <module>
    from ..ggplot import ggplot
  File "/opt/kotori/lib/python3.9/site-packages/ggplot/ggplot.py", line 13, in <module>
    from .aes import aes
  File "/opt/kotori/lib/python3.9/site-packages/ggplot/aes.py", line 11, in <module>
    from . import utils
  File "/opt/kotori/lib/python3.9/site-packages/ggplot/utils.py", line 81, in <module>
    pd.tslib.Timestamp,
  File "/opt/kotori/lib/python3.9/site-packages/pandas/__init__.py", line 244, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'tslib'
```

**Comment by amotl** [comment]
At https://github.com/yhat/ggpy/issues/662#issuecomment-1304755013, @AAAlex-123 suggests to `pip install plotnine`. Maybe it is a drop-in replacement / successor package?

-- https://pypi.org/project/plotnine/

**Comment by amotl** [comment]
We fixed it on behalf of GH-147.
